### PR TITLE
Update doortarget.md

### PR DESCRIPTION
**Pull request by SirCabby**

### CODE REVIEW

**Comment by brainiac** [comment]
according to the code, /doortarget only takes `id #`, `clear` or a name
if name is empty, then it takes nearest.

**Comment by brainiac** [comment]
so "nearest" and "target" aren't valid, and will be interpreted as a name.

**Comment by SirCabby** [comment]
ah, mixed it with switch

**Comment by SirCabby** [comment]
@brainiac review should be ready again

**Pull request merged**
